spring:
  application:
    name: patchflow-api

  datasource:
    url: jdbc:postgresql://ep-old-art-abe53zun-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require&stringtype=unspecified
    username: neondb_owner
    password: npg_Xm8uYBbDdV0a
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: PatchFlowHikariCP
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 1
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        globally_quoted_identifiers: true
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: ${PORT:8080}

  error:
    include-message: always
    include-binding-errors: always

app:
  upload-dir: ${UPLOAD_DIR:./uploads}

  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results: DEBUG
    org.springframework.jdbc: INFO
    com.zaxxer.hikari: INFO