-- CreateEnum
CREATE TYPE "task_status" AS ENUM ('OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'APPROVED', 'PENDING_DEPLOYMENT', 'DEPLOYED', 'PENDING_VERIFICATION', 'VERIFIED', 'CLOSED', 'REJECTED');

-- CreateEnum
CREATE TYPE "user_role" AS ENUM ('SUPER_ADMIN', 'CLIENT', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VERIFIER');

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'DEVELOPER';
