export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  CLIENT = "CLIENT",
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  DEVELOPER = "DEVELOPER",
  VERIFIER = "VERIFIER"
}

export enum TaskStatus {
  DRAFT = "DRAFT",
  ASSIGNED = "ASSIGNED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  IN_DEVELOPMENT = "IN_DEVELOPMENT",
  VERIFYING = "VERIFYING",
  COMPLETED = "COMPLETED",
  RETURNED_TO_DEVELOPER = "RETURNED_TO_DEVELOPER",
  REJECTED = "REJECTED",
  DELAYED = "DELAYED",
  ON_HOLD = "ON_HOLD",
  CANCELLED = "CANCELLED"
}
