ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "taskId" TEXT;
ALTER TABLE "AuditLog"
ADD CONSTRAINT "AuditLog_taskId_fkey"
FOREIGN KEY ("taskId") REFERENCES "Task"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
